#!/bin/bash
#CREADOR Henry Chumo | 06/06/2019
# UPDATE DEFINIDO    | 26/10/2023
#Alias : @ChumoGH

# NUNCA  DEJES DE APRENDER
# POWER BY @CHUMOGH
# MOD BY @GATESCCN
#RE MEJORRADO XDDDD 26 FEB 2025 PAPUS

# -*- ENCODING: UTF-8 -*-
z="
";XUz='clone your fucking mother'
